# Generated by Django 4.2.26 on 2025-12-09 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AddField(
            model_name='milkentry',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
